"""empty message

Revision ID: 95ca2471f534
Revises: c4954ea41d47
Create Date: 2023-03-01 14:49:47.787241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ca2471f534'
down_revision = 'c4954ea41d47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikemodels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=50), nullable=True),
    sa.Column('model', sa.VARCHAR(length=50), nullable=True),
    sa.Column('engine_capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('engine_capacity > 0', name='check_engine_capacity_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'model', name='_brand_model_uc')
    )
    op.create_index(op.f('ix_bikemodels_model'), 'bikemodels', ['model'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=50), nullable=False),
    sa.Column('birth_day', sa.Date(), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bikes',
    sa.Column('number', sa.VARCHAR(length=12), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), nullable=True),
    sa.Column('born_year', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=250), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', name='bikestatus'), nullable=True),
    sa.Column('cost_per_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('born_year > 0', name='check_born_year_positive'),
    sa.CheckConstraint('cost_per_day > 0', name='check_cost_per_day_positive'),
    sa.CheckConstraint('mileage >= 0', name='check_mileage_positive'),
    sa.ForeignKeyConstraint(['model_id'], ['bikemodels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('number'),
    sa.UniqueConstraint('number')
    )
    op.create_table('orders',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('bike_number', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_begin', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETE', 'RESERVATION', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('date_end > date_end', name='check_dates_positive'),
    sa.ForeignKeyConstraint(['bike_number'], ['bikes.number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('bikes')
    op.drop_table('users')
    op.drop_index(op.f('ix_bikemodels_model'), table_name='bikemodels')
    op.drop_table('bikemodels')
    # ### end Alembic commands ###
